name: Release obsidian plugin
on:
    workflow_dispatch:
        inputs:
            bump:
                default: false
                description: "Bump version based on semantic release"
                type: boolean
                required: false
            beta:
                default: false
                description: "Make a beta release"
                type: boolean
                required: false
    push:
        tags:
            - "*"
permissions:
    contents: write
jobs:
    echo:
        runs-on: ubuntu-latest
        outputs:
            beta: ${{ steps.is_beta.outputs.BETA}}
        steps:
            - name: echo
              run: |
                  echo EVENT NAME =  ${{ github.event_name }}
                  echo BETA = ${{ inputs.beta || false}}
                  echo BUMP = ${{ inputs.bump || false}}
            - name: beta
              id: is_beta
              run: echo "BETA=$(node -p "require('./package.json').version.includes('-')")" >> "$GITHUB_OUTPUT"

    release:
        if: (github.event_name == 'push') || (github.event_name == 'workflow_dispatch' && !inputs.bump)
        uses: lisandra-dev/reusable-workflows/.github/workflows/obsidian-plugin-release.yaml@main
        needs: echo
        with:
            PLUGIN_NAME: "obsidian-mkdocs-publisher"
            STYLE: true
            BETA: ${{ needs.echo.outputs.beta }}
            SUBMODULE: true
            CACHE: "pnpm"
        secrets:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    bump-version-and-release:
        if: ${{ inputs.bump }}
        needs: echo
        uses: lisandra-dev/reusable-workflows/.github/workflows/obsidian-plugin-bump-version.yaml@main
        with:
            PLUGIN_NAME: "obsidian-mkdocs-publisher"
            STYLE: true
            BETA: ${{ needs.echo.outputs.beta }}
            SUBMODULE: true
            CACHE: "pnpm"
        secrets:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
