name: Publish Obsidian Plugin
"on":
  workflow_dispatch:
  push:
    tags:
      - "*"
inputs:
  bump:
    default: false
    description: "Bump version"
    type: boolean

permissions:
  contents: write
jobs:
  publish:
    if: ${{ !inputs.bump }}
    uses: lisandra-dev/reusable-workflows/.github/workflows/obsidian-plugin-publish.yaml@main
    with:
      PLUGIN_NAME: "obsidian-mkdocs-publisher"
      STYLE: true
    secrets: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  bump:
    if: inputs.bump
    uses: lisandra-dev/reusable-workflows/.github/workflows/bump.yaml@main
    with:
      PLUGIN_NAME: obsidian-mkdocs-publisher
      STYLE: true
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}