name: Release obsidian plugin
on:
  workflow_dispatch:
    inputs:
      bump:
        default: false
        description: "Bump version based on semantic release"
        type: boolean
        required: false
      beta:
        default: false
        description: "Make a beta release"
        type: boolean
        required: false
  push:
    tags:
      - "*"
permissions:
  contents: write
jobs:
  echo:
    if: ${{ github.env.ACT }}
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo ${{ github.event_name }}
          echo ${{ inputs.beta }}
          echo ${{ inputs.bump }}
  get-version:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push') || (github.event_name == 'workflow_dispatch' && !inputs.bump)
    outputs:
      beta: ${{ steps.get-beta.outputs.beta }}
    steps:
      - name: Node init
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get version
        id: get-beta
        run: |
          $version = $(node -p "require('./package.json').version")
          if [[ $version == *"-"* ]]; then
            echo "beta=true" >> $GITHUB_OUTPUT
          else
            echo "beta=false" >> $GITHUB_OUTPUT
          fi
  release:
    if: (github.event_name == 'push') || (github.event_name == 'workflow_dispatch' && !inputs.bump)
    needs: get-version
    uses: lisandra-dev/reusable-workflows/.github/workflows/obsidian-plugin-release.yaml@main
    with:
        PLUGIN_NAME: "obsidian-mkdocs-publisher"
        STYLE: true
        BETA: ${{ needs.get-version.outputs.beta }}
    secrets: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  bump-version-and-release:
    if: ${{ inputs.bump }}
    uses: lisandra-dev/reusable-workflows/.github/workflows/obsidian-plugin-bump-version.yaml@main
    with:
        PLUGIN_NAME: "obsidian-mkdocs-publisher"
        STYLE: true
        BETA: ${{ inputs.beta }}
    secrets: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
